# SCRIPT PARA EVALUAR NUMEROS PARES E IMPARES CON COLORES ASCII
# SIN USAR COLORAMA Y CON MENSAJES EN MAYUSCULAS

# CODIGOS DE COLOR ASCII
COLOR_VERDE = "\033[32m"
COLOR_AMARILLO = "\033[33m"
COLOR_VERDE_BRILLANTE = "\033[92m"
COLOR_RESET = "\033[0m"

# FUNCION PARA EVALUAR EL NUMERO
def evaluar_numero(numero):
    # EVALUAR SI ES 10
    if numero == 10:
        print(f"{COLOR_VERDE}EL NUMERO INGRESADO ES 10{COLOR_RESET}")
    # EVALUAR SI ES 7 (COMODIN)
    elif numero == 7:
        print(f"{COLOR_VERDE_BRILLANTE}SE HA INGRESADO UN COMODIN{COLOR_RESET}")
    # EVALUAR SI ES PAR
    elif (numero % 2) == 0:
        print(f"{COLOR_VERDE}EL NUMERO INGRESADO ES PAR{COLOR_RESET}")
    # EVALUAR SI ES IMPAR
    else:
        print(f"{COLOR_AMARILLO}EL NUMERO INGRESADO ES IMPAR{COLOR_RESET}")

# FUNCION PRINCIPAL
def main():
    # SOLICITAR NUMERO AL USUARIO
    entrada = int(input("INGRESE EL NUMERO A EVALUAR: "))
    # LLAMAR A LA FUNCION EVALUAR_NUMERO
    evaluar_numero(entrada)

# PUNTO DE ENTRADA DEL PROGRAMA
if __name__ == "__main__":
    main()